### ISSUE TITLE
Unable to access other available methods

### ISSUE THREAD

**Issue by piyushwalia** [BiserStoilov/scroll-animations#3]
Not able to use [isVisible](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbarisvisible) method from smooth scrollbar library.

Tried putting the same method in [public](https://github.com/BiserStoilov/scroll-animations/blob/0b4c05d028325790ff5d4a461f51cbbb53b8e9ae/src/index-with-out-dependencies.js#L143) but still not able to use it.

Here is the sample codepen link where I am using isVisible method
https://codepen.io/piyushwalia/pen/aeyowK

Could anyone please help me.
Thanks in advance.

**Comment by gopalvirat** [comment]
@piyushwalia facing the same issue.

**Comment by BiserStoilov** [comment]
Hi @piyushwalia, @gopalvirat,

try this code in  scroll-animations/demo/src/js/demo.js 

```javascript
import scrollAnimations from '../../../src/index';
import TweenMax from 'gsap/TweenMax';
const scrollAnimation = scrollAnimations({
    element: '#scroll-animation-content'
});
const parent = document.querySelector('.center');
window.addEventListener('resize', () => {
    TweenMax.set(['#scroll-animation-content', '.title'], { height: parent.clientHeight });
});
const smoothScrollBar = scrollAnimation.getScrollBar();
const element = document.querySelector('#your-element');
smoothScrollBar.addListener(() => {
    console.log(smoothScrollBar.isVisible(element));
});
```

**Comment by piyushwalia** [comment]
Getting the same error.

`demo.js:15 Uncaught ReferenceError: scrollAnimation is not defined`

**Comment by piyushwalia** [comment]
It worked on the codepen link shared above https://codepen.io/piyushwalia/pen/aeyowK.
but didn't worked on demo.js file so my problem is solved.

Thanks for the help and hope it helps others like people are usually looking for the solution to add animation to smooth scrollbar.
https://github.com/dixonandmoe/rellax/issues/122#issuecomment-516488474
