### ISSUE TITLE
Unable to make it run

### ISSUE THREAD

**Issue by webgiftdev** [BiserStoilov/scroll-animations#4]
First of all thank you for this share. I use smooth-scrollbar however i tried to combine it with WOW.js library with no success at all. 
I came through this nice repository of yours using AOS however i can not make it run either. Tried to run the demo attached here with no success again! Is there a way to have all of the technologies and changes needed to one js file for example?

Thank you!

**Comment by BiserStoilov** [comment]
git clone https://github.com/BiserStoilov/scroll-animations.git

cd scroll-animations

npm install

npm run demo


Demo run at http://localhost:8080/
